first_num = int(input())
second_num = int(input())

print(first_num + second_num)
print(first_num - second_num)
print(second_num - first_num)
print(first_num * second_num)
print(first_num / second_num)
print(second_num % first_num)
print(first_num ** second_num)